#!/usr/bin/env bash
#
# Copy Vera Design into packages/vera_design and switch Project360 to the real
# Vera embed (screens, TabShell styling, assets). Safe to re-run when Vera updates.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-}"

if [[ -z "$SRC" ]]; then
  echo "Usage: $0 /path/to/vera_design" >&2
  exit 1
fi

if [[ ! -f "$SRC/pubspec.yaml" ]]; then
  echo "Not a Flutter package: $SRC/pubspec.yaml missing" >&2
  exit 1
fi

DEST="$ROOT/packages/vera_design"
mkdir -p "$DEST"

echo "Copying Vera Design from $SRC -> $DEST"
rsync -a --delete \
  --exclude .git \
  --exclude build \
  --exclude .dart_tool \
  --exclude .idea \
  "$SRC/" "$DEST/"

MARKER="$DEST/lib/shells/tab_shell.dart"
if [[ ! -f "$MARKER" ]]; then
  echo "This does not look like Vera Design (missing lib/shells/tab_shell.dart)." >&2
  exit 1
fi

echo "Enabling vendored Vera UI…"
cat > "$ROOT/lib/generated/vera_vendored.dart" <<'EOF'
/// Generated by tool/vendor_vera_design.sh — do not edit by hand.
const bool kVeraVendored = true;
EOF

copy_template() {
  local template="$1"
  local target="$2"
  if [[ ! -f "$template" ]]; then
    echo "Missing template: $template" >&2
    exit 1
  fi
  cp "$template" "$target"
}

copy_template "$ROOT/lib/features/pitch/pitch_router_vera.impl.dart.template" \
  "$ROOT/lib/features/pitch/pitch_router_vera.impl.dart"
copy_template "$ROOT/lib/features/pitch/home_module_gate_vera.dart.template" \
  "$ROOT/lib/features/pitch/home_module_gate_vera.dart"
copy_template "$ROOT/lib/features/embed/preview_app.impl.dart.template" \
  "$ROOT/lib/features/embed/preview_app.impl.dart"
copy_template "$ROOT/lib/features/vera/full_vera_router.impl.dart.template" \
  "$ROOT/lib/features/vera/full_vera_router.impl.dart"
copy_template "$ROOT/lib/features/vera/brand_vera_colors.dart.template" \
  "$ROOT/lib/features/vera/brand_vera_colors.dart"

PUBSPEC="$ROOT/pubspec.yaml"
if ! grep -q 'path: packages/vera_design' "$PUBSPEC"; then
  python3 - "$PUBSPEC" <<'PY'
import sys
from pathlib import Path
path = Path(sys.argv[1])
text = path.read_text()
needle = "  shared_preferences: ^2.5.5\n"
insert = needle + "  vera_design:\n    path: packages/vera_design\n"
if needle not in text:
    raise SystemExit("Could not patch pubspec.yaml — shared_preferences block missing")
path.write_text(text.replace(needle, insert, 1))
PY
fi

if ! grep -q 'packages/vera_design/assets/images/' "$PUBSPEC"; then
  python3 - "$PUBSPEC" <<'PY'
import sys
from pathlib import Path
path = Path(sys.argv[1])
text = path.read_text()
needle = "    - assets/images/\n"
insert = needle + "    - packages/vera_design/assets/images/\n"
if needle not in text:
    raise SystemExit("Could not patch pubspec assets")
path.write_text(text.replace(needle, insert, 1))
PY
fi

cd "$ROOT"
flutter pub get

echo ""
echo "TabShell API (pitch preview uses this for glass tabs):"
rg "class TabShell" -A 12 "$DEST/lib/shells/tab_shell.dart" || true

echo ""
echo "Done. Real Vera screens are enabled (kVeraVendored = true)."
echo "Commit packages/vera_design/ when you are ready to drop the external Vera repo."
